track germs - work in process
mordechaigellis/track-germ pull request #5
Opened 2023-02-21 15:10 UTC by LeahBineth

2023-02-28 15:05 UTC, mordechaigellis requested changes
missing some basic sql

2023-02-28 15:05 UTC, mordechaigellis commented on 1 tables.sql
> +	GermName varchar(200) not null,
missing pk

2023-02-28 15:05 UTC, mordechaigellis commented on 2 sample data.sql
> +select 'Norovirus', 'human'
missing insert

2023-02-28 15:10 UTC, LeahBineth commented on 1 tables.sql
> +	GermName varchar(200) not null,
okay, I'll fix

2023-02-28 15:13 UTC, LeahBineth commented on 2 sample data.sql
> +select 'Norovirus', 'human'
will fix

2023-03-06 14:50 UTC, LeahBineth commented on 1 tables.sql
> +	GermName varchar(200) not null,
fixed...

2023-03-06 14:50 UTC, LeahBineth commented on 2 sample data.sql
> +select 'Norovirus', 'human'
fixed - https://github.com/mordechaigellis/track-germ/pull/5/commits/7c5045b88e7f519e4322ca2db469a86010cb8e49

2023-03-06 14:59 UTC, mordechaigellis commented on 1 tables.sql
> +	GermName varchar(200) not null,
good

2023-03-06 14:59 UTC, mordechaigellis commented on 2 sample data.sql
> +select 'Norovirus', 'human'
all good

2023-03-06 14:59 UTC, mordechaigellis approved these changes

2023-09-06 08:59 UTC, closed without merging