Implementation of track-germs
mordechaigellis/track-germ pull request #8
Opened 2023-02-21 15:10 UTC by YiskaPanksi

I did the work, please review

2023-02-28 15:03 UTC, mordechaigellis requested changes
missing basic sql

2023-02-28 15:03 UTC, mordechaigellis commented on 1 tables.sql
> +create table dbo.germ(
missing pk

2023-02-28 15:03 UTC, mordechaigellis commented on 2 sample data.sql
> +select 'Norovirus', 'human'
missing insert

2023-02-28 15:09 UTC, YiskaPanksi reviewed
Agreed on one and disagreed on other....

2023-02-28 15:09 UTC, YiskaPanksi commented on 1 tables.sql
> +create table dbo.germ(
PK not needed....

2023-02-28 15:09 UTC, YiskaPanksi commented on 2 sample data.sql
> +select 'Norovirus', 'human'
Will fix

2023-03-06 14:43 UTC, mordechaigellis commented on 1 tables.sql
> +create table dbo.germ(
it is needed please do it

2023-03-06 14:45 UTC, YiskaPanksi commented on 2 sample data.sql
> +select 'Norovirus', 'human'
Fixed

2023-03-06 14:46 UTC, YiskaPanksi commented on 1 tables.sql
> +create table dbo.germ(
Fixed

2023-03-06 14:51 UTC, mordechaigellis commented on 2 sample data.sql
> +select 'Norovirus', 'human'
all good

2023-03-06 14:51 UTC, mordechaigellis commented on 1 tables.sql
> +create table dbo.germ(
all good

2023-03-06 14:53 UTC, mordechaigellis approved these changes
all is reviewed and good

2023-03-06 15:05 UTC, mordechaigellis commented
Mark :85% deduct points because we had several attempts...

2023-03-06 15:06 UTC, closed without merging